### PR TITLE
Added macros

### PR DESCRIPTION
**Pull request by dimtass**
One of the features I'm using a lot in br@y's terminal is the macros.
Since, I'm using also Linux a lot and CuteCom is a better solution than
running bray's terminal with wine, I've added a similar functionality in CuteCom.

I've tested on Ubuntu 18.04 and Qt 5.11.1

Dimitris

### CODE REVIEW

**Comment by cyc1ingsir** [comment]
Hi Dimitris,
this looks interesting. I need to look at the PR a bit more closely before I merge.
One small thing I noticed: The entry you added at the changelog is filed under version 0.45 I released a couple of days ago. Could you please move it to the second line from the top, just under version 0.50.
Something else: Not knowing the other terminal application, it's not quite obvious what to enter inside the columns of the macro settings window. e.g. what does the checkbox do? Maybe some column headers would be helpful.

**Comment by dimtass** [comment]
Hi cyc1insir,

before you merge I would like to fill the tooltips to make it more clear.

Regarding the other application is the one that is referred at the end of the README.md file of cutecom. That was the reason I've added the macros, because it was really useful in Bray's terminal.

Regarding the controls, the first textbox is the serial command that is stored in the macro. The second textbox is the name of the macro which is also displayed on the the next column which is the button for the macro. So if you change the macro name, then that is also changing button's label on the main app and on the macro settings window. By pressing either of these button the command in the first column is sent on the serial.

The two last columns is the timer. The first one is the time interval in microseconds. The default value is 1000ms. That means that if the checkbox is checked then the timer is triggered and every 1000ms the macro is sent. Each timer is independent, therefore it timeouts (and sends the serial command) right after the moment it expires. Therefore, if you trigger multiple timers that have 1000ms timeout then they won't expire at the same time. To disable the time you need to uncheck the checkbox.

Pretty much that's it.

**Comment by cyc1ingsir** [comment]
Hi Dimitris,

thanks for the changes. These make it very clear now. :+1:  I never used br@y's terminal. Alex, CuteCom's original author probalby has.

Still, there is a merge conflict within the Changlog. The top of that file should look like 
```
0.50.0, tba , 2018
-added macros support similar to br@y's terminal

0.45.0, June 17 , 2018
-Enable input of Crl characters using a popup or Ctrl+<x>
```
It seems, you forked just before I packaged the last release (0.45.) at June 17th. So please pull in the master of this repo
(git pull git://github.com/neundorf/CuteCom.git master)

One last remark. Could you please run format.sh on `macrosettings.cpp`. Clang-format will format the help text slightly different.
Cheers,
cyc1ingsir

**Comment by dimtass** [comment]
Hi cyc1ingsir,
I've fixed the conflict and re-format the code. It should be OK now.

Also, I think that there's something wrong with sessions, but that doesn't have to do with my code. I'll create a bug report for this.

**Comment by dimtass** [comment]
Sure, I could do that. I agree that unused options should be hidden.
Also a plugin system with some UI and peripheral hooks and would be also a nice option, so users can add their own plugins.

**Pull request merged**
