### PR TITLE
Added a new byte counter plugin

### PR DESCRIPTION
**Pull request by dimtass**
Hi Meinhard,

I've added a new plugin for counting Tx/Rx bytes.
It also supports to store a snapshot of any current values, in order to
compare different Tx/Rx transactions.

I've also fixed a small issue when the macro plugin was unloaded.

Regards,
Dimitris

### CODE REVIEW

**Comment by cyc1ingsir** [comment]
Hi Dimitris,
looks good to me. On minor finding: Does it look like this at yours? It seems to me the ByteCounter plugin frame could do with a couple of pixles below the button as padding.
layout_bytecounter

**Comment by dimtass** [comment]
I'll have a look and add some more pixels. I remember I've tried to make this one slim.
@cyc1ingsir before you merge, let me have a look at this and fix it:
https://github.com/neundorf/CuteCom/issues/75

**Comment by dimtass** [comment]
@cyc1ingsir I've fixed this. I've added a comment on the other issue.

**Comment by dimtass** [comment]
Hi Meinhard,

no worries. I've did he changes and pushed.
Generally, I like the SIGNAL()/SLOT() method because it's more transparent
and it's easy to
have an overview of the parameters for each function, which makes debugging
much easier.

If there's anything else then don't hesitate to tell me.

Regards,
Dimitris

**Pull request merged**
